### ISSUE TITLE
[Model] CVAE

### ISSUE THREAD

**Issue by hzhwcmhf** [thu-coai/contk#11]
Refer to Learning Discourse-level Diversity for Neural Dialog Models using Conditional Variational Autoencoders

**Comment by hzhwcmhf** [comment]
Dataloader
* Ubuntu
* Switchboard (new)

Metric 
* perplexity
* blue prec\recall
* embedding prec\recall
* DA prec\recall

Metrics refer to papers

**Comment by ZhihongShao** [comment]
Will be finished before Jan. 14.

**Comment by hzhwcmhf** [comment]
Done
