### ISSUE TITLE
[Maintenance] Check the license of dataset

### ISSUE THREAD

**Issue by hzhwcmhf** [thu-coai/contk#116]
* mscoco
* OpenSubtitles
* UbuntuCorpus

Check if we can redistribution the data.

**Comment by kepei1106** [comment]
mscoco: Creative Commons Attribution 4.0 License
OpenSubtitles: no license. Cite the original paper when we use this dataset.
UbuntuCorpus: Apache License 2.0

**Comment by hzhwcmhf** [comment]
mscoco: 需要署名，提供协议的链接，然后标明是否对原始作品做过修改

**Comment by hzhwcmhf** [comment]
Done
