### ISSUE TITLE
[Enhancement] enhance metric test

### ISSUE THREAD

**Issue by hzhwcmhf** [thu-coai/contk#57]
https://github.com/thu-coai/contk/blob/e6e3d641766e4ae2111f41e742be206cc8684d2c/tests/dataloader/test_metric.py#L61-L76

* make the length of sentence different in different turns. 
* make the length of turn different in different batches

**Comment by hzhwcmhf** [comment]
* Test default arguments and custom arguments

**Comment by hzhwcmhf** [comment]
Here are some conditions. You should cover all the conditions or even the combination of conditions.

Try to tell which conditions are covered by which tests, and write comments

Perplexity metric

* default argument or custom argument
* gen_prob padded or jagged
* reference list or numpy
* gen_prob list or numpy
* random_check
* full_check

MultiTurnPerplexity metric

* default argument or custom argument
* gen_prob padded or jagged
* reference list or numpy
* gen_prob padded or jagged, list or numpy
* random_check
* full_check

BleuCorpusMetric

* default argument or custom argument 
* ref list or numpy
* ref empty or not
* gen empty or not

MultiTurnBleuMetric
* default argument or custom argument 
* reference list or numpy
* ref empty or not
* gen empty or not

**Comment by z123z123d** [comment]
![image](https://user-images.githubusercontent.com/19621030/51842489-f6b3ab00-234b-11e9-96a8-338efee58209.png)

**Comment by hzhwcmhf** [comment]
Done
